### PR TITLE
Replace deprecated usage of Ember.Evented

### PR DESCRIPTION
**Pull request by mayatron**
- Addesses https://github.com/danielspaniel/ember-data-change-tracker/issues/64

### CODE REVIEW

**Comment by danielspaniel** [comment]
thanks @mayatron , i was not sure if you would do the PR,  but glad you did.

**Comment by mayatron** [comment]
@danielspaniel sorry, my fix is not working as intended. There are two problems:

1. The `ember-data:evented-api-usage` deprecations are still present, due to `this._super(...arguments)` being incorrectly called in these events.

2. If any of these four hooks (`ready`, `didCreate`, `didUpdate`, `didDelete`) are defined in a user's model, the corresponding Ember Data Change Tracker event defined will not be fired, which will likely break expected functionality.

I'm looking into possible fixes, and hope to open a new PR, with tests, but you may want to consider reverting this for now.

**Comment by danielspaniel** [comment]
I will just mark this patch release 0.9.1 as not great .. adn wait for your new fix ( hard to revert npm published versions )

**Comment by mayatron** [comment]
Thanks @danielspaniel 

I haven't been able to figure out a way yet to have these hooks continue to work on the models which are being reopened, as well as within the `Model.reopen()` function in this add-on. Will post this to other channels to see if anyone has ideas.

**Comment by danielspaniel** [comment]
Thanks for trying @mayatron .. I figured it might be tricky

**Comment by mayatron** [comment]
After reading [Deprecate Usage of Ember Evented in Ember Data](https://github.com/emberjs/rfcs/blob/master/text/0329-deprecated-ember-evented-in-ember-data.md), specifically the following couple points:

> The following lifecycle methods on DS.Model will also be deprecated: becameError, becameInvalid, didCreate, didDelete, didLoad, didUpdate, ready, rolledBack. [...] The drawback to making this change is existing code that takes advantage of the Ember Data lifecycle events will need to be updated to use a different pattern.

I'm not sure what the path forward is. It seems like addressing this might require a more of a (tricky) architectural change than a syntax update. :-/

**Comment by runspired** [comment]
> I'm not sure what the path forward is. It seems like addressing this might require a more of a (tricky) architectural change than a syntax update. :-/

Confirm.

I would recommend that change-tracker should ship a custom RecordData and (once available) a custom RecordClass implementation.

- Diff information would be tracked via RecordData
- a Custom Record class could expose new methods or alternative buffering strategies (e.g. you could have separate class instances for showing dirty vs clean state)

**Comment by runspired** [comment]
Although I'd also say this would likely hugely reduce the size and complexity of this library

**Comment by danielspaniel** [comment]
@mayatron ,  do you feel like taking a crack at this ( I am on vacation for another 10 days ) so it will be at least 2 weeks till I get to it.

**Comment by danielspaniel** [comment]
@runspired , let me know when there is documentation for the RecordData class, because I only see info on RecordReference class

**Comment by danielspaniel** [comment]
@loxmys , can you work on this?

**Comment by rwwagner90** [comment]
We're hitting these deprecations still. @runspired are there any examples we could follow to try to implement the new RecordData stuff?

**Pull request merged**
