### PR TITLE
Dirtiness computed

### PR DESCRIPTION
**Pull request by janmisek**
introduces following computed properties:

- hasDirtyRelations
- hasDirtyAttributes
- isDirty

Optionally it could be also decoupled to mixin

### CODE REVIEW

**Comment by danielspaniel** [comment]
This is pretty clever, because I can not quite figure out what is going on. But overall, it looks pretty slick.  
 Should we be worried about performance on this .. don't think so but any thoughts on it. 
 Nice tests too. 
 Can you add one more test to check for after saving model .. that the dirty state is reset. 
 If you not sure how I can do it too.  I would just use mockUpdate('user') and test again ( pretty simple )

**Comment by janmisek** [comment]
> performance

To be honest I did not test it. Its truth that any change to relations or attributes triggers recomputation of  dirtiness props. But observers are created per attributes and relations seperately. Also recomputation is actually executed only in case binding to isDirty, hasDirtyAttributes or hasDirtyRelations exists. Also I think at least for hasDirtyAttributes native overriden property was for sure faster as it was probably based on ember-data internals.

> saving model

There was indeed test failure after model saved. I added some event handler to enforce recomputation of dirtiness properties

```
dirtinessListeners: Ember.on(
     'didCreate',
     'didUpdate',
     'didLoad',
     'didDelete',
     function () {
       this.notifyPropertyChange('hasDirtyAttributes');
       this.notifyPropertyChange('hasDirtyRelations');
     }),
```

**Comment by danielspaniel** [comment]
awesome @janmisek .. this was a really fun PR. Me like. I did not incorporate these latest changes yet because i messed around with things to add the concept that the isDirty property could be optional. Can you check it out on master and let me know what you think. 
 Maybe it is too ridiculous to make it optional but I figured it would be nice because people freak out about performance and this sort of shuts those people up.

**Comment by danielspaniel** [comment]
Also, I wrote the same test as you ( sorry I was not available all day .. no internet in sight. ) but was strange because I saw the failure too when I did the save test .. but now it works even without any notifyPropertyChange ( which I did too .. but took it out ) since tests passed without it

**Comment by janmisek** [comment]
Thank you for merging it. I am going to switch my app back from fork.

> optional / performance
Makes sense. Still until anything is bound to computed, performance should not be affected.

> docs
I think docs need to be updated as well.

> dirtinessListeners
Lets wait a bit, whether its needed or not. I experienced the issue always. Also its expected behaviour, consider eg: reloaded model. In case same values as dirty one came from reloaded data, recomputation of dirtiness will not be triggered.

**Comment by danielspaniel** [comment]
There is ONE big problem with the isDirty / isDirtyAttributes cp. 

```
test('#isDirty computed works on object/json/custom attributes (with auto save model)', function(assert) {
  Ember.run(() => {
    let info = {foo: 1};
    let user = make('user', {info});

    assert.equal(user.get('isDirty'), false);
    assert.equal(user.get('hasDirtyAttributes'), false);

    user.set('info.foo', 2);

    assert.equal(user.get('isDirty'), true);
    assert.equal(user.get('hasDirtyAttributes'), true);
  });
});
```

This test fails. I just thought of it a few hours ago. Any idea how to fix that?

**Comment by janmisek** [comment]
Hmm I see.

What would be generally best Approach by my opinion is to rewrite changes() to be computed and bind dirtiness computed to changes computed then. I did not look to internals so I do not know how much effort it would be. But regarding performance there will be no hit until anybody bind to changes or dirtiness  (eg: in template)

Another approach is to watch serialized string value of the object. I think from what I have seen in code that  this is the way how you detect nested object changes ? is it ?

**Comment by danielspaniel** [comment]
Oh .. yes, right .. I like that 2nd way .. to watch the serialized changes .. yes the change tracking for those attributes serializes to string

**Comment by danielspaniel** [comment]
I guess I would have to watch the property on the model 
 '-change-tracker.info'
the model holds the saved values in a object whose key is  'change-tracker'

**Comment by danielspaniel** [comment]
Although I am not sure how to watch that value exactly. You think you try it? I am trying to .. see who  gets it first. The first option probably wont work unless this can be figured out anyway .. because this one is the key tricky part.

**Comment by danielspaniel** [comment]
By the way @janmisek .. if you want to talk about it on screen hero let me know. That is funner sometimes.

**Comment by danielspaniel** [comment]
Yes, this idea is not that great.  It would force someone to tell you what to track which takes the whole fun away from how simple it used to be and should be. 
Oh well, thanks for trying though. There might be another way to do it. 
 I guess we can just think about it more.

**Comment by danielspaniel** [comment]
Am closing this since most of the changes from here are incorporated in the code.
 Someone can open a new PR for improving isDirty for object attributes

**Pull request closed without merging**
